import type { Exercise } from "./types";

// Starter exercise library for the prototype. In the real build these live in a
// database and are managed through the admin UI. Video URLs are placeholders —
// swap them for your own unlisted YouTube links.
export const EXERCISES: Exercise[] = [
  // ---------- WARMUPS ----------
  {
    id: "wu-dynamic",
    name: "Dynamic Movement Warmup",
    description:
      "Progressive jog, high knees, butt kicks, lunges, and arm circles to raise heart rate and mobilize shoulders and hips.",
    focusZones: ["conditioning"],
    ageGroups: ["U12", "U14", "U16", "U18", "Adult"],
    levels: ["rec", "school", "club", "elite"],
    gender: "any",
    difficulty: 1,
    minPlayers: 2,
    maxPlayers: 30,
    durationMin: 8,
    equipment: [],
    phases: ["prep", "build", "competition", "peak", "recovery"],
    type: "warmup",
    videoUrl: "https://www.youtube.com/watch?v=UBMk30rjy0o",
  },
  {
    id: "wu-pepper",
    name: "Partner Pepper",
    description:
      "Pairs continuously pass, set, and controlled-hit to each other. Great ball-contact warmup that touches every core skill.",
    focusZones: ["passing", "setting", "defense"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 2,
    minPlayers: 2,
    maxPlayers: 30,
    durationMin: 8,
    equipment: ["balls"],
    phases: ["prep", "build", "competition", "peak"],
    type: "warmup",
    videoUrl: "https://www.youtube.com/watch?v=1P4iBz9v2xU",
  },
  {
    id: "wu-mobility",
    name: "Band Shoulder Activation",
    description:
      "Resistance-band external rotations, pull-aparts, and scapular retractions to prime the shoulder for hitting and serving.",
    focusZones: ["conditioning"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 1,
    minPlayers: 1,
    maxPlayers: 30,
    durationMin: 6,
    equipment: ["bands"],
    phases: ["prep", "build", "competition", "peak", "recovery"],
    type: "warmup",
  },

  // ---------- SERVING ----------
  {
    id: "sv-targets",
    name: "Serve to Zones",
    description:
      "Place cones/targets in zones 1, 5, and 6. Players serve for accuracy, scoring points for hitting targets.",
    focusZones: ["serving"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 2,
    minPlayers: 2,
    maxPlayers: 16,
    durationMin: 12,
    equipment: ["balls", "net", "targets"],
    phases: ["prep", "build", "competition", "peak"],
    type: "skill",
    videoUrl: "https://www.youtube.com/watch?v=Rt3Qb0m9E1g",
  },
  {
    id: "sv-pressure",
    name: "Serving Under Pressure",
    description:
      "Players must make consecutive serves in a row; a miss resets the count. Builds mental toughness and consistency.",
    focusZones: ["serving"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 3,
    minPlayers: 4,
    maxPlayers: 16,
    durationMin: 12,
    equipment: ["balls", "net"],
    phases: ["build", "competition", "peak"],
    type: "skill",
  },
  {
    id: "sv-intro",
    name: "Underhand Serve Progression",
    description:
      "Teach the underhand serve close to the net, then step back progressively. Ideal for beginners building confidence.",
    focusZones: ["serving"],
    ageGroups: ["U12", "U14"],
    levels: ["rec", "school"],
    gender: "any",
    difficulty: 1,
    minPlayers: 2,
    maxPlayers: 20,
    durationMin: 12,
    equipment: ["balls", "net"],
    phases: ["prep", "build"],
    type: "skill",
    videoUrl: "https://www.youtube.com/watch?v=Wj9m0N0Xm0k",
  },

  // ---------- PASSING / SERVE-RECEIVE ----------
  {
    id: "ps-butterfly",
    name: "Butterfly Passing",
    description:
      "Players pass a served ball to target, follow their ball to the opposite side, and rotate through lines continuously.",
    focusZones: ["passing", "serve-receive"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 2,
    minPlayers: 6,
    maxPlayers: 18,
    durationMin: 14,
    equipment: ["balls", "net"],
    phases: ["prep", "build", "competition"],
    type: "skill",
    videoUrl: "https://www.youtube.com/watch?v=8m0N9m0oXbA",
  },
  {
    id: "ps-serverreceive",
    name: "Serve-Receive Formations",
    description:
      "Run full 3- and 2-passer serve-receive patterns against live serves, calling and executing rotations.",
    focusZones: ["serve-receive", "passing", "systems"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 4,
    minPlayers: 8,
    maxPlayers: 14,
    durationMin: 16,
    equipment: ["balls", "net"],
    phases: ["build", "competition", "peak"],
    type: "tactical",
  },
  {
    id: "ps-wall",
    name: "Wall Passing Reps",
    description:
      "Solo controlled forearm passes against a wall focusing on platform angle and consistent contact.",
    focusZones: ["passing"],
    ageGroups: ["U12", "U14", "U16"],
    levels: ["rec", "school"],
    gender: "any",
    difficulty: 1,
    minPlayers: 1,
    maxPlayers: 30,
    durationMin: 10,
    equipment: ["balls"],
    phases: ["prep", "build"],
    type: "skill",
  },

  // ---------- SETTING ----------
  {
    id: "st-triangle",
    name: "Triangle Setting",
    description:
      "Three players set in a triangle, moving to the ball and squaring shoulders to the next target.",
    focusZones: ["setting"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 2,
    minPlayers: 3,
    maxPlayers: 15,
    durationMin: 12,
    equipment: ["balls"],
    phases: ["prep", "build", "competition"],
    type: "skill",
    videoUrl: "https://www.youtube.com/watch?v=5qap5aO4i9A",
  },
  {
    id: "st-transition",
    name: "Setter Transition to Net",
    description:
      "Setter starts in base defense, transitions to the net on a dig, and delivers accurate sets to pins.",
    focusZones: ["setting", "systems"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 4,
    minPlayers: 4,
    maxPlayers: 12,
    durationMin: 14,
    equipment: ["balls", "net"],
    phases: ["build", "competition", "peak"],
    type: "tactical",
  },

  // ---------- ATTACKING ----------
  {
    id: "at-approach",
    name: "Approach & Swing Footwork",
    description:
      "Repetition of the 4-step approach and arm swing mechanics, self-tossed then set-fed.",
    focusZones: ["attacking"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 2,
    minPlayers: 2,
    maxPlayers: 16,
    durationMin: 14,
    equipment: ["balls", "net"],
    phases: ["prep", "build", "competition"],
    type: "skill",
    videoUrl: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ",
  },
  {
    id: "at-lines",
    name: "Hitting Lines",
    description:
      "Continuous hitting lines from outside, middle, and right side against a coach or setter feed.",
    focusZones: ["attacking"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 3,
    minPlayers: 6,
    maxPlayers: 16,
    durationMin: 16,
    equipment: ["balls", "net", "cart"],
    phases: ["build", "competition", "peak"],
    type: "skill",
  },
  {
    id: "at-tooling",
    name: "Hitting Around the Block",
    description:
      "Attackers work on tooling the block, high hands, and tips versus a set two-player block.",
    focusZones: ["attacking"],
    ageGroups: ["U18", "Adult"],
    levels: ["elite"],
    gender: "any",
    difficulty: 5,
    minPlayers: 6,
    maxPlayers: 14,
    durationMin: 16,
    equipment: ["balls", "net"],
    phases: ["competition", "peak"],
    type: "tactical",
  },

  // ---------- BLOCKING ----------
  {
    id: "bl-footwork",
    name: "Blocking Footwork Ladder",
    description:
      "Lateral shuffle and crossover blocking footwork along the net, penetrating hands over on each stop.",
    focusZones: ["blocking"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 2,
    minPlayers: 2,
    maxPlayers: 12,
    durationMin: 12,
    equipment: ["net"],
    phases: ["prep", "build", "competition"],
    type: "skill",
  },
  {
    id: "bl-read",
    name: "Read Blocking vs Setter",
    description:
      "Blockers read the setter's hands and release to the correct pin, forming a solid two-person block.",
    focusZones: ["blocking", "systems"],
    ageGroups: ["U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 4,
    minPlayers: 6,
    maxPlayers: 14,
    durationMin: 14,
    equipment: ["balls", "net"],
    phases: ["build", "competition", "peak"],
    type: "tactical",
  },

  // ---------- DEFENSE ----------
  {
    id: "df-dig",
    name: "Coach-on-Box Digging",
    description:
      "Coach hits down from a box; defenders read, move, and dig to target from base defensive positions.",
    focusZones: ["defense"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 3,
    minPlayers: 4,
    maxPlayers: 12,
    durationMin: 14,
    equipment: ["balls", "net"],
    phases: ["prep", "build", "competition", "peak"],
    type: "skill",
    videoUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
  },
  {
    id: "df-pursuit",
    name: "Emergency Pursuit Drill",
    description:
      "Players sprint, dive, and pursue errant balls, emphasizing effort and platform control on tough digs.",
    focusZones: ["defense", "conditioning"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 4,
    minPlayers: 3,
    maxPlayers: 12,
    durationMin: 10,
    equipment: ["balls"],
    phases: ["prep", "build", "competition"],
    type: "skill",
  },

  // ---------- SYSTEMS / SCRIMMAGE ----------
  {
    id: "sys-6v6",
    name: "6v6 Wash Game",
    description:
      "Scored wash scrimmage: teams must win a serve plus a rally to score, reinforcing complete point sequences.",
    focusZones: ["systems", "serve-receive", "attacking"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 4,
    minPlayers: 12,
    maxPlayers: 14,
    durationMin: 20,
    equipment: ["balls", "net"],
    phases: ["build", "competition", "peak"],
    type: "scrimmage",
    videoUrl: "https://www.youtube.com/watch?v=L_jWHffIx5E",
  },
  {
    id: "sys-queen",
    name: "Queen of the Court",
    description:
      "Rotating small-sided game where winners stay on the champion side; fast-paced, competitive, fun.",
    focusZones: ["systems", "defense", "attacking"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 3,
    minPlayers: 9,
    maxPlayers: 18,
    durationMin: 18,
    equipment: ["balls", "net"],
    phases: ["build", "competition", "peak", "recovery"],
    type: "scrimmage",
  },
  {
    id: "sys-mini",
    name: "Mini 3v3 Games",
    description:
      "Small-court 3v3 games maximizing touches and decision-making for developing players.",
    focusZones: ["systems", "passing", "setting"],
    ageGroups: ["U12", "U14", "U16"],
    levels: ["rec", "school"],
    gender: "any",
    difficulty: 2,
    minPlayers: 6,
    maxPlayers: 18,
    durationMin: 16,
    equipment: ["balls", "net"],
    phases: ["prep", "build", "competition", "recovery"],
    type: "scrimmage",
  },

  // ---------- CONDITIONING ----------
  {
    id: "cd-jump",
    name: "Plyometric Jump Circuit",
    description:
      "Box jumps, broad jumps, and approach jumps in timed sets to build explosive vertical power.",
    focusZones: ["conditioning"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 3,
    minPlayers: 1,
    maxPlayers: 20,
    durationMin: 12,
    equipment: ["cones"],
    phases: ["prep", "build"],
    type: "conditioning",
  },
  {
    id: "cd-agility",
    name: "Court Agility Shuttles",
    description:
      "Line-to-line shuttle sprints and defensive slides to build court speed and change of direction.",
    focusZones: ["conditioning"],
    ageGroups: ["U14", "U16", "U18", "Adult"],
    levels: ["school", "club", "elite"],
    gender: "any",
    difficulty: 2,
    minPlayers: 1,
    maxPlayers: 30,
    durationMin: 10,
    equipment: ["cones"],
    phases: ["prep", "build", "competition"],
    type: "conditioning",
  },

  // ---------- COOLDOWNS ----------
  {
    id: "cl-stretch",
    name: "Static Stretch & Debrief",
    description:
      "Full-body static stretching while the coach recaps session goals and previews the next session.",
    focusZones: ["conditioning"],
    ageGroups: ["U12", "U14", "U16", "U18", "Adult"],
    levels: ["rec", "school", "club", "elite"],
    gender: "any",
    difficulty: 1,
    minPlayers: 1,
    maxPlayers: 30,
    durationMin: 8,
    equipment: [],
    phases: ["prep", "build", "competition", "peak", "recovery"],
    type: "cooldown",
  },
  {
    id: "cl-mobility",
    name: "Foam Roll & Mobility",
    description:
      "Guided foam rolling and mobility flow targeting shoulders, hips, and ankles to aid recovery.",
    focusZones: ["conditioning"],
    ageGroups: ["U16", "U18", "Adult"],
    levels: ["club", "elite"],
    gender: "any",
    difficulty: 1,
    minPlayers: 1,
    maxPlayers: 30,
    durationMin: 8,
    equipment: ["bands"],
    phases: ["prep", "build", "competition", "peak", "recovery"],
    type: "cooldown",
  },
];
